name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          script_stop: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker system prune -af

            rm -r pierek-frontend

            git clone git@github.com:Pierek-Software/pierek-frontend.git

            cd pierek-frontend

            docker build -t pierek-frontend .
            docker rm -f pierek-frontend-container
            docker run --restart always -d \
            -p 4000:4000 \
            --name pierek-frontend-container \
            pierek-frontend:latest
